### ISSUE TITLE
"Changed the F9 help menu to auto select the about ptpm page"

### ISSUE THREAD

**Issue by martinloeffen** [PTPM/MTASA#12]
When I press F9 it still opens heligrab first. I think it might be because I don't automatically sign in to my PTPM account and when the login dialog is open, only the heligrab tab exists and the PTPM tab does not.

**Comment by RempRemp** [comment]
Yea, that sounds right. The helpmanager will just show whichever tab was first (or whatever you last had open that session). That commit just changes the PTPM tab itself to auto-select the about PTPM section (since the tab is split into multiple "pages") when it is opened. I suppose auto selecting the PTPM tab would also be a smart thing to do.

**Comment by RempRemp** [comment]
Fixed in a429b068fff1d54e4cedf494e52876da82e4acde
