### ISSUE TITLE
PM death doesn't set interior (correctly) for end of round scene

### ISSUE THREAD

**Issue by martinloeffen** [PTPM/MTASA#14]
If the PM dies in an interior and every players camera is set to the murder scene, they'll be looking at the PM floating in the sky instead of the interior of the building

**Comment by martinloeffen** [comment]
Video of the issue https://stjohnsmorgue.rip/s/DFkxR9V7.mp4
Especially pay attention to the position, at 0:56 uhm2 kept falling even though the round had ended. Could it be related to being out of bounds, and being teleported back? I also sometimes get the "You are out of bounds" message post-pm mortem

**Comment by martinloeffen** [comment]
I also notice now that the interior marker is visible on uhm2 at 0:25 and 0:56
Could it be related to the camera matrix being set, but not the character position and the area isn't streamed in (not sure if that's a thing still but it was in SAMP iirc)

**Comment by RempRemp** [comment]
The world in mta is streamed around the camera rather than the player, but clearly there are some issues with it inside interiors. Commit 204fce0935561a0a75cf7bcb3fa1d288810b451d forces the player interior & dimension and that seems to mostly fix it. I have noticed sometimes it doesn't load interior furniture (perhaps for some reason that is tied to player location, so you aren't in streaming range, rather than camera), but that is fairly minor.

**Comment by martinloeffen** [comment]
If the furniture loading could be fixed by teleporting everyone into each other behind the camera, and it'd be like in SA:MP, and you'd hear all the peds yelling "Man can't you see" etc, that'd be the return of an amazing glitch/feature and I would definitely support that 😂

**Comment by martinloeffen** [comment]
Does appear to be fixed!
