### ISSUE TITLE
Timer isn't exactly correct but only after you join

### ISSUE THREAD

**Issue by anonymous-d0z42ujxuog5** [PTPM/MTASA#34]
When you join an ongoing game, the timer will be off by a couple of seconds.

First pointed out by Raid:
> [20:00] <&Fats> is the prime rib su[[posed to win with 10 seconds left
[20:00] <&Fats> because that just happened

And later verified to occur by uhm: a different PM in a different round won with 0:03 on the timer. But also only the first round of the night, which the PM happened to win.

Then after the round, it's synced back again and the timer will be right.

**Comment by RempRemp** [comment]
Probably because of the network congestion when you first join the server (i.e. when it downloads everything). The event it sends to the client that syncs up the timer will get delayed with all the other network traffic and appear out of sync. It will always be out of sync a little, e.g. by whatever your ping is, it's just more obvious the first time you join
